### ISSUE TITLE
EOF error when using shared_dict in multiple workers.

### ISSUE THREAD

**Issue by kexul** [ptrblck/pytorch_misc#4]
When the size of shared data is very big, then read/write this dict will raise an EOF error. 
Related discuss in stackoverflow: https://stackoverflow.com/questions/4534687/python-sharing-huge-dictionaries-using-multiprocessing 
Is there any better solution?

**Comment by ptrblck** [comment]
Hi @kexul,

I'm not sure what the best approach would be, but maybe you could increase your shared memory?

**Comment by kexul** [comment]
Thank you peter, I'll try it.

**Comment by kexul** [comment]
I found that I may need to login as root to modify shared memory setting, that's some kind of privilege I won't have for a long time...
